version: "3.3"

networks:
  php-study-case-net:
    driver: bridge

services:
  study-case-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-study-case
    container_name: php-study-case
    networks:
      - php-study-case-net
    ports:
      - 7100:80
    volumes:
      - .:/app
    working_dir: /app