version: "3.3"

networks:
  php-teste-ster-net:
    driver: bridge

services:
  teste-ster-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-teste-ster
    container_name: php-teste-ster
    networks:
      - php-teste-ster-net
    ports:
      - 7100:80
    volumes:
      - .:/app
    working_dir: /app